/**
 * HelloApply: Cloud Edition
 * VERSION: 4.2.0 (Self-Orchestrating Timeout Defense Edition)
 * LAST UPDATED: 18/05/2026 19:15
 * 
 * New:
 * - Self-Orchestrating Timeout Defense: Integrates a real-time elapsed timer checking against a safety execution threshold (260s) to exit gracefully, preserving state and preventing hard Google execution limits under high-volume alerts!
 * - Rapid Test Exit: Immediately terminates all nested email processing loops the second the Test Mode quota (1 LinkedIn + 1 HelloWork) is achieved, conserving execution time.
 * - Google Docs Safe Clearance Engine: Completely resolves the structural 'Can't remove the last paragraph' exception by safely removing children backwards while retaining and re-using the first paragraph for the Markdown H1 heading!
 * - Markdown-to-Doc Generation Engine: Clears the template and programmatically reconstructs the CV and Cover Letter from the ground up using Markdown generated by Gemini, enforcing absolute language consistency (no mixed Franglais) and professional ATS spacing, margins, and typography!
 * - Premium Document Styles: Renders Navy Blue section headers, horizontal rules, justified paragraphs, line spacing 1.15, and bullet list items programmatically!
 * - Fully Operational Job Links: Preserves critical query parameters (such as otpToken, trackingId, and redirect codes) in cleanUrl to ensure Gmail draft job links remain fully operational and bypass login walls!
 * - Emulates Gemini 3.1 Pro Gold Standard: Enforces the world-class executive writing style, action verbs, and prestigious tone from the Gemini 3.1 Pro reference CV across all documents!
 */

// --- CONFIGURATION ---
const TEST_MODE = true; // Set to true to run infinite tests on the latest emails

const ROOT_FOLDER_NAME = "Candidature Express";
const INPUT_FOLDER_NAME = "input";
const OUTPUT_FOLDER_NAME = "output";

const MASTER_CV_NAME = 'SilvereMartinMichiellot-CV-full'; 
const TEMPLATE_CV_NAME = 'SilvereMartinMichiellot-CV-1pageATS-2026';
const TEMPLATE_LETTER_NAME = 'Lettre de motivation Silvère Martin-Michiellot 2026b';

const TRACKING_SHEET_NAME = 'Suivi_Candidatures';
const MIN_MATCH_SCORE = 80; 

// --- USER PREFERENCES ---
const PREFERENCES = {
  location: "Lorient, France",
  radiusLocal: 20, 
  radiusRegional: 50,
  allowFullRemote: true,
  preferredRegions: ["Europe", "World"]
};

/**
 * Main Entry Point
 * TEST_MODE: processes at most 1 LinkedIn job + 1 HelloWork job, then stops.
 */
function main() {
  const startTime = new Date().getTime();
  const MAX_EXECUTION_TIME_MS = 260000; // 4.3 minutes, extremely safe threshold to avoid the Google 6 min timeout

  const props = PropertiesService.getScriptProperties();
  const lastRunStr = props.getProperty('LAST_RUN_TIMESTAMP');
  const lastRun = TEST_MODE ? new Date(Date.now() - 48 * 60 * 60 * 1000) : (lastRunStr ? new Date(lastRunStr) : new Date(Date.now() - 12 * 60 * 60 * 1000));

  console.log(`[START] Scanning since ${lastRun.toLocaleString()}...`);
  if (TEST_MODE) console.warn('⚠️ [MODE TEST] Limité à 1 offre LinkedIn + 1 offre HelloWork maximum.');

  let threads = [];
  const queries = [
    'subject:"nouvelles offres" "HelloWork"',
    'subject:"alerte" "LinkedIn"',
    'from:jobalerts-noreply@linkedin.com',
    'from:notification@emails.hellowork.com'
  ];
  
  queries.forEach(q => {
    const result = GmailApp.search(q, 0, TEST_MODE ? 5 : 10);
    threads = threads.concat(result);
  });
  
  threads = threads.filter((t, index, self) => index === self.findIndex((th) => t.getId() === th.getId()));

  const root = getOrCreateFolder(ROOT_FOLDER_NAME);
  const inputFolder = getOrCreateFolderIn(root, INPUT_FOLDER_NAME);
  const outputFolder = getOrCreateFolderIn(root, OUTPUT_FOLDER_NAME);
  
  const masterCV = readAnyFileIn(inputFolder, MASTER_CV_NAME);
  const cvTemplateText = readAnyFileIn(inputFolder, TEMPLATE_CV_NAME);
  const letterTemplateText = readAnyFileIn(inputFolder, TEMPLATE_LETTER_NAME);

  if (!masterCV) {
    console.error("[ERROR] Master CV not found. Aborting.");
    return;
  }

  // TEST_MODE quota: max 1 LinkedIn + 1 HelloWork
  let testLinkedInDone = false;
  let testHelloWorkDone = false;

  for (const thread of threads) {
    if (TEST_MODE && testLinkedInDone && testHelloWorkDone) break;
    
    // Safety check: close to Google execution limit (6 min)
    if (new Date().getTime() - startTime > MAX_EXECUTION_TIME_MS) {
      console.log(`[TIMEOUT] Proche de la limite Apps Script (6 min). Arrêt gracieux, la suite au prochain passage.`);
      break;
    }

    if (!TEST_MODE && thread.getLastMessageDate() <= lastRun) continue;

    const messages = thread.getMessages();
    for (const message of messages) {
      if (TEST_MODE && testLinkedInDone && testHelloWorkDone) break;
      if (new Date().getTime() - startTime > MAX_EXECUTION_TIME_MS) break;
      
      if (!TEST_MODE && message.getDate() <= lastRun) continue;

      const subject = message.getSubject();
      const body = message.getPlainBody();
      const jobUrls = extractJobUrls(body);
      
      console.log(`[MAIL] Analysing email: "${subject}"`);

      for (let rawUrl of jobUrls) {
        if (TEST_MODE && testLinkedInDone && testHelloWorkDone) break;
        if (new Date().getTime() - startTime > MAX_EXECUTION_TIME_MS) break;

        let url = cleanUrl(rawUrl);
        const isLinkedIn = url.includes('linkedin.com');
        const isHelloWork = url.includes('hellowork.com');

        // TEST_MODE: skip if we already processed this source
        if (TEST_MODE && isLinkedIn && testLinkedInDone) { console.log('[TEST] LinkedIn quota atteint, skip.'); continue; }
        if (TEST_MODE && isHelloWork && testHelloWorkDone) { console.log('[TEST] HelloWork quota atteint, skip.'); continue; }
        
        // Resolve click-tracking redirections for HelloWork to get the clean final page link
        if (url.includes('emails.hellowork.com/clic') || url.includes('hellowork.com/redirect')) {
          console.log(`[RESOLVING] Resolving redirect for: ${url}`);
          url = resolveRedirects(url);
          url = cleanUrl(url);
          console.log(`[RESOLVED] Final URL: ${url}`);
        }
        
        const jobId = getJobId(url);
        
        if (isJobProcessed(jobId)) {
          console.log(`[SKIP] Job already processed: ${jobId}`);
          continue;
        }

        try {
          let description = fetchJobDescription(url);
          let context = description;
          
          if (!description || description.includes("authWall") || description.includes("login")) {
            console.warn(`[WARN] Login wall detected for ${url}. Using email content as fallback.`);
            context = `[URL: ${url}]\n[EMAIL SUBJECT: ${subject}]\n[EMAIL BODY: ${body}]`;
          }

          const analysis = analyzeAndTailor(context, masterCV, cvTemplateText, letterTemplateText, url);
          if (analysis) {
            analysis.url = url;
            analysis.source = url.includes('linkedin.com') ? 'LinkedIn' : 'HelloWork';
            analysis.raw_description = context; // Save full context for the draft copy
            
            if (analysis.decision === "Postuler" && analysis.score >= MIN_MATCH_SCORE) {
              processJob(inputFolder, outputFolder, analysis);
            } else {
              console.log(`[IGNORED] ${analysis.position} at ${analysis.company} (Score: ${analysis.score}%, Decision: ${analysis.decision})`);
              logToSheet(outputFolder, analysis, "", ""); // Always log rejected/ignored jobs
            }
            
            // Mark job as processed to prevent duplicates
            markJobProcessed(jobId);
            
            // TEST_MODE: flag source as done
            if (TEST_MODE && isLinkedIn) { testLinkedInDone = true; console.log('[TEST] LinkedIn traité. Quota atteint.'); }
            if (TEST_MODE && isHelloWork) { testHelloWorkDone = true; console.log('[TEST] HelloWork traité. Quota atteint.'); }
          }
        } catch (e) { console.error(`[ERROR] ${url}: ${e.message}`); }
      }
    }
  }
  if (!TEST_MODE) props.setProperty('LAST_RUN_TIMESTAMP', new Date().toISOString());
}

function analyzeAndTailor(context, masterCV, cvTemplateText, letterTemplateText, originalUrl) {
  const prompt = `
    TASK: Generate a fully tailored, executive-level CV and Cover Letter in Markdown format from the candidate's Master CV and the target job description.
    
    JOB DESCRIPTION:
    ${context}
    
    MASTER CV / SOURCE KNOWLEDGE (THE ONLY SOURCE OF TRUTH):
    ${masterCV}
    
    INSTRUCTIONS FOR LANGUAGE & EXECUTIVE WRITING:
    1. Language Detection & Consistency (No mixed "Franglais" documents):
       - Detect the language of the job description or context.
       - If it is in English, BOTH the CV and the Cover Letter MUST be completely in English. You must translate any French terms, headings, dates, and locations from the templates/master CV into perfect natural English.
       - For the Cover Letter in English:
         * The date block MUST be in English (e.g., "Lorient, May 18, 2026"). Never write "Lorient, le...".
         * The greeting MUST be in English (e.g., "Dear Hiring Manager," or "Dear Avanade Team,"). Never write "Madame, Monsieur,".
         * The closing salutation MUST be in English (e.g., "Sincerely," or "Best regards,"). Never mix French closings ("Je vous prie d'agréer...") with English titles!
       - If it is in French, both documents MUST be entirely in French.
         * The date block MUST be in French (e.g., "Lorient, le 18 mai 2026").
         * The greeting MUST be "Madame, Monsieur,".
         * The closing salutation MUST be "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.".
       
    2. Executive Writing Style (Emulate the Gold Standard tone):
       - Emulate the high-impact, prestigious tone of the Gemini 3.1 Pro reference CV below.
       - Write extremely rich, strategic, and metric-heavy bullet points and summaries from the Master CV details. Do not write short or generic bullet points.
       
    [GOLD STANDARD CV EXAMPLE]:
    "Silvère MARTIN-MICHIELLOT Lorient, France (Remote) | 07 67 81 52 02 | silvere.martin@gmail.com 
    LinkedIn: linkedin.com/in/silvere-martin-michiellot-65b6a95/ | GitHub: github.com/silveremartin-dev
    
    ARCHITECTE SENIOR IA AGENTIQUE & SYSTÈMES DISTRIBUÉS (ICOE)
    Architecte et Principal Engineer avec plus de 30 ans d'expertise dans le pilotage et la refonte de systèmes d'information complexes. Pionnier de l'ingénierie logicielle augmentée par IA (Expert Google Antigravity), alliant un double cursus scientifique en neurosciences et intelligence artificielle à une capacité d'exécution hors norme : division par 5 des cycles de livraison et automatisation de 80% du cycle de vie des applications (tests, documentation). Expert de la modernisation de legacy critique et de la conception d'architectures distribuées multi-cloud hautes performances.
    
    COMPÉTENCES CLÉS
    Architectures IA & Frameworks Agentiques : Orchestration multi-agents, frameworks autonomes et semi-autonomes (Google Antigravity, architectures de type LangChain/AutoGen), LLMs, Prompt Engineering, patterns RAG, et bases de données vectorielles.
    Ingénierie Logicielle & Systèmes Distribués : Expertise Java (J2SE 1.0 à 25+), Python, C#, Micro-services, architectures orientées événements, API REST/MCP, calcul scientifique distribué haute performance.
    Modernisation de Legacy & Delivery Lifecycle : Audit et refactoring de codes patrimoniaux critiques, automatisation end-to-end des phases d'analyse, build, test (TDD), documentation et déploiement via agents IA.
    Environnements Cloud & MLOps/DevOps : Maîtrise multi-cloud (GCP, AWS, architectures hybrides), conteneurisation (Docker, Kubernetes), CI/CD, observabilité, et gouvernance/sécurité des données (RGPD, chiffrement).
    Leadership Technique & Advisory : Direction d'équipes d'ingénierie (jusqu'à 8 développeurs en environnement Agile/Scrum), relation client stratégique (AMOA), vulgarisation de concepts IA complexes auprès d'audiences techniques et exécutives."
    ========================================================================

    3. Formatting Instructions (Markdown for rendering):
       - For the CV:
         * Use "# " for "Silvère MARTIN-MICHIELLOT" (Centered at the top).
         * Use a normal paragraph below it for the exact contact details: "8 Rue Jean Marie Toulliou, 56100 Lorient | 07 67 81 52 02 | silvere.martin@gmail.com"
         * Use a normal paragraph below that for LinkedIn and GitHub links: "LinkedIn: linkedin.com/in/silvere-martin-michiellot-65b6a95/ | GitHub: github.com/silveremartin-dev"
         * MANDATORY CV TITLE: Use "## [Exact Target Position in Capital Letters]" (e.g. "## RESPONSABLE INFORMATIQUE") immediately below the contact block. This trône dynamically at the top!
         * STRICT FORBIDDEN LINE: Never write "Méthodes : Agile (Scrum/Lean)..." or similar under the contact block.
         * Use "## " for other main sections (e.g. "## PROFIL PROFESSIONNEL", "## COMPÉTENCES CLÉS", "## EXPÉRIENCES PROFESSIONNELLES", "## FORMATION & LANGUES", "## ENVIRONNEMENT TECHNIQUE").
         * Use "### " for job titles/companies or sub-sections (e.g. "### Responsable Informatique — Equitive | Lorient | 10/2012 - 11/2023").
         * STRICT LIST FORMATting: ALWAYS use the standard bullet point syntax ("- " or "* ") for all lists. Never use numbered lists ("1.", "2.", "3.") anywhere in the CV!
         * STRICT CHRONOLOGICAL ORDER: The experiences MUST be sorted in strict reverse chronological order (the most recent first, e.g. 2025 then 2023 then 2012...).
         * HIGHLIGHT LANGUAGES: Always highlight the candidate's linguistic masteries with clear CEFR/levels (e.g. "- **Anglais** : Niveau C2 (TOEFL 267), Bilingue", "- **Espagnol** : Niveau B2").
         * Use double asterisks "**" to bold key terms, technologies, and metrics.
       
       - For the Cover Letter:
         * Include the sender details block at the very top (and nowhere else):
           Silvère Martin-Michiellot
           8 Rue Jean Marie Toulliou, 56100 Lorient
           silvere.martin@gmail.com | 07 67 81 52 02
           LinkedIn: linkedin.com/in/silvere-martin-michiellot-65b6a95/ | GitHub: github.com/silveremartin-dev/
         * STRICT NO DUPLICATION: Do not create any title like "# Silvère Martin-Michiellot" or duplicate the name on the right side of the cover letter.
         * Leave a blank line after the sender details block, then write the Date line (e.g., "Lorient, le 18 mai 2026").
         * Include the recipient details cleanly on a single line (never split it or repeat Lorient):
           À l'attention du Responsable du Recrutement - [Company]
         * Use "## " for the Subject Line in bold and in standard black text (e.g., "## **Objet : Candidature au poste de...**"). No horizontal rules or custom blue colors below the subject!
         * Leave a blank line before the final signature ("Silvère Martin-Michiellot") to separate it cleanly from the text.
         * Use double asterisks "**" to bold key terms or company names for emphasis.
        
    Return JSON only:
    {
      "company": "Real Company Name (extracted from context)",
      "position": "Exact Job Title (extracted from context)",
      "score": 0-100,
      "reasoning": "Detailed technical critique of the match...",
      "decision": "Postuler" or "Ignorer",
      "job_description_clean": "Cleaned job description in plain text...",
      "language": "en" or "fr",
      "cv_markdown": "Full, complete tailored CV in Markdown format, following the styling rules...",
      "letter_markdown": "Full, complete tailored Cover Letter in Markdown format..."
    }
  `;
  return callGemini(prompt);
}

/**
 * URL Transformation & Fetching
 */
function fetchJobDescription(url) {
  try {
    const options = {
      'muteHttpExceptions': true,
      'headers': {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'
      }
    };
    const response = UrlFetchApp.fetch(url, options);
    const html = response.getContentText();
    
    if (html.includes("authWall") || html.includes("login") || html.includes("Sign in")) return "authWall";
    
    return html.replace(/<script\b[^>]*>([\s\S]*?)<\/script>/gmi, "").replace(/<style\b[^>]*>([\s\S]*?)<\/style>/gmi, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().substring(0, 8000);
  } catch (e) { return null; }
}

/**
 * Process Job
 */
function processJob(inputFolder, outputFolder, job) {
  let cvDocUrl = ""; let lmDocUrl = ""; let attachments = [];
  try {
    const rand = Math.floor(Math.random() * 900000) + 10000;
    const cvName = `SilvereMartinMichiellot-CV-2026-${rand}`;
    const lmName = `SilvereMartinMichiellot-LM-2026-${rand}`;
    
    // Process complete generation from Markdown
    const cvResult = generateFilesFromTemplate(inputFolder, outputFolder, TEMPLATE_CV_NAME, job.cv_markdown || "", cvName);
    const lmResult = generateFilesFromTemplate(inputFolder, outputFolder, TEMPLATE_LETTER_NAME, job.letter_markdown || "", lmName);
    
    cvDocUrl = cvResult.docUrl; 
    lmDocUrl = lmResult.docUrl; 
    attachments = [cvResult.pdfBlob, lmResult.pdfBlob];
    
    createDraft(job, attachments);
  } catch (e) { console.error(`[ERROR] Processing ${job.company}: ${e.message}`); }
  logToSheet(outputFolder, job, cvDocUrl, lmDocUrl);
}

/**
 * Create Gmail Draft (Embeds a beautifully cleaned & structured job description copy)
 */
function createDraft(job, attachments) {
  const subject = `[Candidature ${job.source}] - ${job.position} - ${job.company} (${job.score}%)`;
  const htmlBody = `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; border: 1px solid #e2e8f0; padding: 25px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
      <p style="font-size: 1.1em; margin-top: 0;">Bonjour Silvère,</p>
      <p>Voici ta candidature personnalisée prête à l'envoi pour le poste de <strong style="color: #2c5282;">${job.position}</strong> chez <strong style="color: #2c5282;">${job.company}</strong>.</p>
      <p>Les fichiers PDF adaptés (CV et Lettre de motivation) sont déjà joints à ce brouillon.</p>
      
      <div style="background: #ebf8ff; padding: 20px; border-left: 5px solid #3182ce; margin: 25px 0; border-radius: 4px;">
        <h3 style="margin-top: 0; color: #2b6cb0; font-size: 1.15em;">[Analyse de l'offre - Match : ${job.score}%]</h3>
        <p style="font-style: italic; color: #2d3748; margin-bottom: 12px;">"${job.reasoning}"</p>
        <p style="margin: 0; font-size: 0.9em;"><a href="${job.url}" style="color: #3182ce; text-decoration: underline; font-weight: bold;">Voir l'offre originale sur ${job.source}</a></p>
      </div>
      
      <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 30px 0;">
      <h4 style="color: #4a5568; margin-bottom: 10px; font-size: 1.1em; border-bottom: 2px solid #edf2f7; padding-bottom: 6px;">Description du poste ciblée :</h4>
      <div style="font-size: 0.9em; color: #2d3748; background: #f7fafc; padding: 18px; border: 1px solid #e2e8f0; border-radius: 8px; white-space: pre-wrap; max-height: 400px; overflow-y: auto; line-height: 1.5;">
${job.job_description_clean || job.raw_description || "Non disponible"}
      </div>

      <p style="margin-top: 25px; font-size: 0.95em; color: #4a5568;">Bien amicalement,<br><strong style="color: #2d3748;">Ton assistant HelloApply</strong></p>
    </div>
  `;
  GmailApp.createDraft("", subject, "", { htmlBody: htmlBody, attachments: attachments });
}
function generateFilesFromTemplate(inputFolder, outputFolder, templateName, markdownText, finalName) {
  const files = inputFolder.getFilesByName(templateName);
  if (!files.hasNext()) throw new Error(`Template ${templateName} introuvable.`);
  const copy = files.next().makeCopy(finalName, outputFolder);
  const doc = DocumentApp.openById(copy.getId());
  const body = doc.getBody();
  
  // Render Markdown beautifully with styles, including robust safe clearing of the template!
  renderMarkdownToDoc(body, markdownText);
  
  doc.saveAndClose();
  const pdfBlob = copy.getAs(MimeType.PDF).setName(finalName + ".pdf");
  outputFolder.createFile(pdfBlob);
  return { docUrl: copy.getUrl(), pdfBlob: pdfBlob };
}

function renderMarkdownToDoc(body, markdownText) {
  // Clear the body safely keeping only the first element, avoiding Google Doc's section clearance constraint!
  const numChildren = body.getNumChildren();
  for (let i = numChildren - 1; i > 0; i--) {
    try {
      body.removeChild(body.getChild(i));
    } catch (e) { /* ignore if not removable */ }
  }
  
  let firstParagraph = null;
  const firstChild = body.getChild(0);
  if (firstChild && firstChild.getType() === DocumentApp.ElementType.PARAGRAPH) {
    firstParagraph = firstChild.asParagraph();
    firstParagraph.setText(" ");
  } else {
    try {
      firstParagraph = body.appendParagraph(" ");
      body.removeChild(firstChild);
    } catch (e) {
      firstParagraph = body.appendParagraph(" ");
    }
  }

  // Set Margins (ATS Standard: 0.5 inch top/bottom, 0.75 inch left/right)
  body.setMarginTop(36);
  body.setMarginBottom(36);
  body.setMarginLeft(54);
  body.setMarginRight(54);
  
  const lines = markdownText.split('\n');
  let isFirstLine = true;
  
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i].trim();
    if (!line) continue;
    
    let p;
    let isHeading1 = line.startsWith('# ');
    let isHeading2 = line.startsWith('## ');
    let isHeading3 = line.startsWith('### ');
    let isListItem = line.startsWith('- ') || line.startsWith('* ');
    
    if (isFirstLine) {
      isFirstLine = false;
      p = firstParagraph;
      
      // If the first line is a bullet item, we append it and safely clean up the empty first paragraph
      if (isListItem) {
        const textVal = line.substring(2).trim() || " ";
        const item = body.appendListItem(textVal);
        
        const style = {};
        style[DocumentApp.Attribute.FONT_FAMILY] = 'Roboto';
        style[DocumentApp.Attribute.FONT_SIZE] = 9.5;
        style[DocumentApp.Attribute.FOREGROUND_COLOR] = '#2D3748';
        style[DocumentApp.Attribute.SPACING_BEFORE] = 2;
        style[DocumentApp.Attribute.SPACING_AFTER] = 2;
        style[DocumentApp.Attribute.LINE_SPACING] = 1.1;
        item.setAttributes(style);
        item.setAlignment(DocumentApp.HorizontalAlignment.JUSTIFY);
        
        formatInlineStyles(item);
        
        try { body.removeChild(firstParagraph); } catch(e) {}
        continue;
      }
    } else {
      if (isListItem) {
        const textVal = line.substring(2).trim() || " ";
        const item = body.appendListItem(textVal);
        
        const style = {};
        style[DocumentApp.Attribute.FONT_FAMILY] = 'Roboto';
        style[DocumentApp.Attribute.FONT_SIZE] = 9.5;
        style[DocumentApp.Attribute.FOREGROUND_COLOR] = '#2D3748';
        style[DocumentApp.Attribute.SPACING_BEFORE] = 2;
        style[DocumentApp.Attribute.SPACING_AFTER] = 2;
        style[DocumentApp.Attribute.LINE_SPACING] = 1.1;
        item.setAttributes(style);
        item.setAlignment(DocumentApp.HorizontalAlignment.JUSTIFY);
        
        formatInlineStyles(item);
        continue;
      } else {
        p = body.appendParagraph(" ");
      }
    }
    
    // Configure paragraph p
    if (isHeading1) {
      const textVal = line.substring(2).trim() || " ";
      p.setText(textVal);
      
      const style = {};
      style[DocumentApp.Attribute.FONT_FAMILY] = 'Roboto';
      style[DocumentApp.Attribute.FONT_SIZE] = 16;
      style[DocumentApp.Attribute.BOLD] = true;
      style[DocumentApp.Attribute.FOREGROUND_COLOR] = '#1A365D'; // Premium dark blue
      style[DocumentApp.Attribute.SPACING_BEFORE] = 12;
      style[DocumentApp.Attribute.SPACING_AFTER] = 4;
      p.setAttributes(style);
      p.setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    } else if (isHeading2) {
      const textVal = line.substring(3).trim() || " ";
      p.setText(textVal);
      
      const style = {};
      style[DocumentApp.Attribute.FONT_FAMILY] = 'Roboto';
      style[DocumentApp.Attribute.FONT_SIZE] = 11;
      style[DocumentApp.Attribute.BOLD] = true;
      style[DocumentApp.Attribute.FOREGROUND_COLOR] = '#2B6CB0'; // Slate Blue
      style[DocumentApp.Attribute.SPACING_BEFORE] = 12;
      style[DocumentApp.Attribute.SPACING_AFTER] = 4;
      p.setAttributes(style);
      p.setAlignment(DocumentApp.HorizontalAlignment.LEFT);
    } else if (isHeading3) {
      const textVal = line.substring(4).trim() || " ";
      p.setText(textVal);
      
      const style = {};
      style[DocumentApp.Attribute.FONT_FAMILY] = 'Roboto';
      style[DocumentApp.Attribute.FONT_SIZE] = 10.5;
      style[DocumentApp.Attribute.BOLD] = true;
      style[DocumentApp.Attribute.FOREGROUND_COLOR] = '#2D3748'; // Charcoal
      style[DocumentApp.Attribute.SPACING_BEFORE] = 8;
      style[DocumentApp.Attribute.SPACING_AFTER] = 2;
      p.setAttributes(style);
      p.setAlignment(DocumentApp.HorizontalAlignment.LEFT);
    } else {
      const textVal = line.trim() || " ";
      p.setText(textVal);
      
      const style = {};
      style[DocumentApp.Attribute.FONT_FAMILY] = 'Roboto';
      style[DocumentApp.Attribute.FONT_SIZE] = 9.5;
      style[DocumentApp.Attribute.FOREGROUND_COLOR] = '#2D3748';
      style[DocumentApp.Attribute.SPACING_BEFORE] = 4;
      style[DocumentApp.Attribute.SPACING_AFTER] = 4;
      style[DocumentApp.Attribute.LINE_SPACING] = 1.15;
      p.setAttributes(style);
      p.setAlignment(DocumentApp.HorizontalAlignment.JUSTIFY);
      
      formatInlineStyles(p);
    }
  }
}

function formatInlineStyles(element) {
  const text = element.getText();
  if (!text.includes('**')) return;
  
  const cleanText = text.replace(/\*\*/g, '') || " ";
  element.setText(cleanText);
  
  const textElement = element.editAsText();
  let regex = /\*\*(.*?)\*\*/g;
  let match;
  let searchFrom = 0;
  while ((match = regex.exec(text)) !== null) {
    const boldText = match[1];
    const start = cleanText.indexOf(boldText, searchFrom);
    if (start !== -1) {
      textElement.setBold(start, start + boldText.length - 1, true);
      // Give bold text a beautiful, premium, consistent slate blue color highlight!
      textElement.setForegroundColor(start, start + boldText.length - 1, '#2B6CB0');
      searchFrom = start + boldText.length;
    }
  }
}

/**
 * Detailed Template Diagnostics to scan all files inside the input folder
 */
function getTemplatesDiagnostic() {
  let log = "=== FILES IN INPUT FOLDER ===\n";
  try {
    const root = DriveApp.getRootFolder().getFoldersByName("Candidature Express").next();
    const inputFolder = root.getFoldersByName("input").next();
    
    const files = inputFolder.getFiles();
    if (!files.hasNext()) {
      log += "No files found in 'input' folder.\n";
    }
    
    while (files.hasNext()) {
      const file = files.next();
      log += `\nFile Name: "${file.getName()}"\n`;
      log += `  - MIME Type: ${file.getMimeType()}\n`;
      log += `  - ID: ${file.getId()}\n`;
      
      if (file.getMimeType() === MimeType.GOOGLE_DOCS) {
        try {
          const doc = DocumentApp.openById(file.getId());
          const body = doc.getBody();
          const text = body.getText();
          
          const matches = text.match(/\{[^}]+\}/g) || [];
          const brackets = text.match(/\[[^\]]+\]/g) || [];
          
          log += `  - Found Braces Placeholders: ${JSON.stringify([...new Set(matches)])}\n`;
          log += `  - Found Brackets Placeholders: ${JSON.stringify([...new Set(brackets)])}\n`;
          log += `  - Plain Text Snippet (first 150 chars): "${text.substring(0, 150).replace(/\n/g, " ")}..."\n`;
        } catch (e) {
          log += `  - [ERROR READING CONTENT]: ${e.message}\n`;
        }
      } else {
        log += "  - [NON-GOOGLE-DOC] (cannot inspect inline text)\n";
      }
    }
  } catch (e) {
    log += `[DIAGNOSTIC ERROR] ${e.message}\n`;
  }
  return log;
}

/**
 * Rolling Job Processed Properties
 */
function isJobProcessed(jobId) {
  if (!jobId) return false;
  const props = PropertiesService.getScriptProperties();
  const processed = JSON.parse(props.getProperty('PROCESSED_JOB_IDS') || '[]');
  return processed.indexOf(jobId) !== -1;
}

function markJobProcessed(jobId) {
  if (!jobId) return;
  const props = PropertiesService.getScriptProperties();
  const processed = JSON.parse(props.getProperty('PROCESSED_JOB_IDS') || '[]');
  if (processed.indexOf(jobId) === -1) {
    processed.push(jobId);
    if (processed.length > 500) processed.shift();
    props.setProperty('PROCESSED_JOB_IDS', JSON.stringify(processed));
  }
}

/**
 * HelloWork click-tracking redirect resolver
 */
function resolveRedirects(url) {
  let currentUrl = url;
  let redirectCount = 0;
  while (redirectCount < 5) {
    try {
      const response = UrlFetchApp.fetch(currentUrl, {
        'followRedirects': false,
        'muteHttpExceptions': true,
        'headers': {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        }
      });
      const code = response.getResponseCode();
      if (code >= 300 && code < 400) {
        const headers = response.getHeaders();
        const location = headers['Location'] || headers['location'];
        if (location) {
          if (location.startsWith('/')) {
            const domain = currentUrl.match(/^https?:\/\/[^\/]+/)[0];
            currentUrl = domain + location;
          } else {
            currentUrl = location;
          }
          redirectCount++;
          continue;
        }
      }
      break;
    } catch (e) {
      console.error("[ERROR] Redirect resolution: " + e.message);
      break;
    }
  }
  return currentUrl;
}

/**
 * URL Sanitizers
 */
function cleanUrl(url) {
  if (!url) return "";
  let clean = url.trim();
  if (clean.includes('linkedin.com/comm/jobs/view/')) {
    clean = clean.replace('linkedin.com/comm/jobs/view/', 'linkedin.com/jobs/view/');
  }
  if (clean.includes('urlRedirection=')) {
    const match = clean.match(/urlRedirection=([^&]+)/);
    if (match) {
      try {
        clean = decodeURIComponent(match[1]);
      } catch (e) { /* ignore and use original */ }
    }
  }
  return clean;
}

function getJobId(url) {
  if (!url) return "";
  const clean = cleanUrl(url);
  const liMatch = clean.match(/\/view\/(\d+)/);
  if (liMatch) return "LI_" + liMatch[1];
  
  const hwMatch = clean.match(/(?:offre-|emplois\/)(\d+)/);
  if (hwMatch) return "HW_" + hwMatch[1];
  
  return clean;
}

function logToSheet(folder, job, cvUrl, lmUrl) {
  let sheetFile; const files = folder.getFilesByName(TRACKING_SHEET_NAME);
  if (files.hasNext()) { sheetFile = SpreadsheetApp.openById(files.next().getId()); } 
  else {
    sheetFile = SpreadsheetApp.create(TRACKING_SHEET_NAME);
    folder.addFile(DriveApp.getFileById(sheetFile.getId()));
    DriveApp.getRootFolder().removeFile(DriveApp.getFileById(sheetFile.getId()));
    sheetFile.getSheets()[0].appendRow(["Date", "Source", "Entreprise", "Poste", "Score", "Lien Offre", "Lien CV (Doc)", "Lien Lettre (Doc)", "Analyse"]);
  }
  const now = new Date();
  const dateTimeStr = now.toLocaleDateString() + " " + now.toLocaleTimeString();
  sheetFile.getSheets()[0].appendRow([dateTimeStr, job.source, job.company, job.position, job.score + "%", job.url, cvUrl, lmUrl, job.reasoning]);
}

function callGemini(prompt) {
  const url = `https://generativelanguage.googleapis.com/v1/models/gemini-3.1-flash-lite:generateContent?key=${GEMINI_API_KEY}`;
  const options = { method: 'post', contentType: 'application/json', payload: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }), muteHttpExceptions: true };
  try {
    const response = UrlFetchApp.fetch(url, options);
    const json = JSON.parse(response.getContentText());
    const outputText = json.candidates[0].content.parts[0].text;
    const match = outputText.match(/\{.*\}/s);
    return JSON.parse(match ? match[0] : outputText);
  } catch (e) { return null; }
}

function extractJobUrls(text) {
  const regex = /https:\/\/[^\s"<>]+/g;
  const matches = text.match(regex) || [];
  return matches.filter(url => {
    const isLinkedIn = url.includes('linkedin.com/');
    const isHelloWork = url.includes('hellowork.com');
    if (isLinkedIn) {
      // Exclusively capture real job posting links containing '/view/' or '/jobs/view/'
      return url.includes('/view/') || url.includes('/jobs/view/');
    }
    if (isHelloWork) {
      // Exclusively capture real click-tracking, redirect or job detail pages
      return url.includes('/clic/') || url.includes('/redirect') || url.includes('/emplois/') || url.includes('/offre-');
    }
    return false;
  });
}

function getOrCreateFolder(name) {
  const folders = DriveApp.getRootFolder().getFoldersByName(name);
  return folders.hasNext() ? folders.next() : DriveApp.getRootFolder().createFolder(name);
}

function getOrCreateFolderIn(parent, name) {
  const folders = parent.getFoldersByName(name);
  return folders.hasNext() ? folders.next() : parent.createFolder(name);
}

function readAnyFileIn(folder, fileName) {
  const files = folder.getFilesByName(fileName);
  if (!files.hasNext()) return null;
  const file = files.next();
  return file.getMimeType() === MimeType.GOOGLE_DOCS ? DocumentApp.openById(file.getId()).getBody().getText() : "";
}
